<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio Pandas (EDA y Unión de Datos)

## Los datos

Para este laboratorio, trabajarás con los siguientes conjuntos de datos:

- **`netflix_originals.csv`**: Contiene información sobre producciones originales de Netflix. Las columnas que nos encontraremos en este conjunto de datos son: 

   - `Title`: Contiene el nombre del título de la producción original de Netflix.

   - `Genre`: Especifica el género o combinación de géneros de la producción.

   - `Premiere`: Indica la fecha de estreno de la producción en Netflix.

   - `Runtime`: Contiene la duración de la producción en minutos.

   - `IMDB Score`: Representa la calificación promedio que la producción ha recibido en la plataforma IMDB.

   - `Language`: Especifica el idioma principal o los idiomas en los que se presenta la producción.

- **`netflix_titles.csv`**: Contiene información sobre una variedad de títulos disponibles en la plataforma Netflix, incluyendo tanto películas como series de televisión. Las columnas que nos encontraremos en este conjunto de datos son:

   - `show_id`: Identificador único para cada título en el dataset.

   - `type`: Especifica el tipo de contenido, ya sea "Movie" (película) o "TV Show" (serie de televisión).

   - `title`: Contiene el nombre del título de la producción.

   - `director`: Muestra el nombre del director del título. Puede estar vacío en algunos casos.

   - `cast`: Lista de actores y actrices que participaron en el título. También puede estar vacío en algunos casos.

   - `country`: País o países donde se produjo el título. Esta columna también puede tener valores faltantes.

   - `date_added`: Fecha en la que el título fue añadido al catálogo de Netflix.

   - `release_year`: Año en que el título fue lanzado o producido.

   - `rating`: Clasificación del contenido en términos de audiencia (por ejemplo, PG-13, TV-MA).

   - `duration`: Duración del título. Para películas, se expresa en minutos (e.g., "90 min") y para series en temporadas (e.g., "2 Seasons").

   - `listed_in`: Categorías o géneros bajo los cuales el título está clasificado (por ejemplo, "Documentaries", "TV Dramas").

   - `description`: Breve sinopsis o descripción del contenido del título.

A lo largo de los laboratorios de Pandas, trabajarás con estos conjuntos de datos (o con los derivados del Laboratorio), algunas de las actividades que realizaremos son:

- Exploración de datos y análisis exploratorio (EDA) para familiarizarse con los conjuntos de datos.

- Realización de uniones entre conjuntos de datos, aplicando diferentes técnicas de *merging* y analizando la relevancia de cada método.

- Uso de funciones de selección y filtrado (`loc`, `iloc`) para extraer información clave.

- Desarrollo de análisis descriptivos y visualización de patrones para comprender mejor las decisiones estratégicas de la plataforma.

----

## Objetivo General de la Serie de Laboratorios



1. **Unión de `netflix_titles.csv` con `netflix_originals.csv`:**

   - **Análisis de contenido original:**  Identificarás los títulos que son producciones originales de Netflix y los compararás con los títulos adquiridos. Este análisis te permitirá:

     - Comparar la diversidad de géneros entre los títulos originales y no originales.

     - Evaluar si ciertos géneros o tipos de contenido (como documentales o series) son más frecuentes en las producciones originales.

     - Investigar si la producción original se concentra en determinados países o idiomas.


   - **Evaluación de contenido:** En esta etapa, explorarás si las producciones originales de Netflix tienden a recibir mejores o peores evaluaciones en comparación con el contenido adquirido. Algunas preguntas que se buscarán responder incluyen:

     - ¿Los títulos originales tienen una calificación promedio superior en plataformas como IMDB?

     - ¿Son las producciones originales más consistentes en términos de calidad percibida?

     - ¿Existen diferencias en la popularidad de los títulos originales según su género o país de origen?


   - **Identificación de tendencias:**  Por último, este análisis te permitirá explorar cómo ha evolucionado la estrategia de contenido de Netflix a lo largo del tiempo. Algunos puntos clave a investigar serán:

     - ¿Cómo ha crecido la producción original en comparación con la adquisición de contenido?

     - ¿Qué géneros o tipos de contenido han recibido mayor inversión en los últimos años?
     
     - ¿Existen patrones en los países o idiomas de las producciones originales, especialmente en relación con la expansión global de Netflix?


----


## Ejercicio: Análisis y Enriquecimiento del Catálogo de Netflix

### Parte 1: Análisis Exploratorio de Datos (EDA)

1. **Carga de los datos:**

   - Deberás cargar los dos conjuntos de datos que te hemos proporcionado para realizar este Laboratorio:

     - `netflix_originals.csv`

     - `netflix_titles.csv`

   Deberás revisar la estructura de cada conjunto de datos utilizando los métodos aprendidos durante la lección.

2. **Análisis de columnas y consistencia:**

   - Deberás hacer un análisis exploratorio de cada uno de los conjuntos de datos. Será obligatorio que incluyas las conclusiones generales obtenidas de cada uno de los análisis exploratorios en el Jupyter Notebook de tus soluciones.

   - Explorar qué columnas contiene cada conjunto de datos y cuáles son sus tipos de datos. Identificar si hay valores nulos o duplicados.

   - Algunas preguntas que nos podemos plantear en esta fase son (recuerda que esto es solo un ejemplo, y que podemos explorar todo lo que queramos/necesitemos para entender lo mejor posible los conjuntos de datos):

      - ¿Cuáles son los tipos de datos de cada columna? Nos puede ayudar a detectar si algún tipo de dato está incorrectamente asignado, como fechas almacenadas como cadenas de texto.

      - ¿Existen valores nulos? ¿En qué columnas están? Este paso es crucial para decidir si deben ser eliminados, rellenados o ignorados.

      - ¿Cuántos títulos únicos hay en cada conjunto de datos? Nos puede permitir verificar si existen títulos duplicados que puedan distorsionar el análisis.

      - ¿Qué géneros tenemos en el conjunto de datos? Esto nos puede ayudar a identificar los géneros más populares o incluso a identificar una posible limpieza de dicha columna para poder extraer conclusiones más claras en nuestro análisis.

### Parte 2: Unión de Datos

1. **Realización de la unión:**

   - Deberás realizar la unión que consideres más apropiada entre `netflix_titles.csv` y `netflix_originals.csv`. Además, deberás justificar el tipo de unión que has realizado.

   - Esto nos ayudará a contestar preguntas más adelente del tipo:

     - ¿Cuántos títulos en `netflix_titles.csv` son producciones originales de Netflix?

     - ¿Hay diferencias significativas en la puntuación de IMDB entre títulos originales y no originales?

### Parte 3: Uso de `loc` e `iloc`

Usando el DataFrame creado en la Parte 2: 

1. **Filtrado de datos con `loc`:**

   - Selecciona todas las filas donde el tipo de contenido sea “Movie”.

   - Muestra solo los títulos (title) y la duración (duration) de todos los contenidos que sean de tipo “TV Show”.

   - Selecciona todas las filas donde el país sea “United States”.

   - Muestra todas las películas (type = “Movie”) y selecciona las columnas title y director.

   - Selecciona los títulos (title) y géneros (listed_in) de todas las producciones lanzadas en 2018.

   - Selecciona las filas donde la columna director esté vacía y muestra solo los títulos (title).

2. **Acceso a datos específicos con `iloc`:**

   - Selecciona las primeras 5 filas del conjunto de datos y muestra solo las columnas title, director y country.

   - Muestra las últimas 5 filas del conjunto de datos y selecciona las columnas title y description.

   - Selecciona las primeras 10 filas del dataset y muestra las columnas desde la segunda hasta la quinta (incluidas). 

   - Muestra las últimas 7 filas del dataset y selecciona las columnas title, director, y country usando índices posicionales.

   - Selecciona las filas desde la 15 hasta la 25 (incluidas) y muestra las primeras 4 columnas.

   - Muestra las filas 20 a 30 y solo las columnas title, release_year, y rating usando índices posicionales.


**NOTA IMPORTANTE**: Antes de terminar el lab, guarda el conjunto de datos creado en la fase de unión para trabajar con el en las siguientes lecciones.

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None) #hace que jupyter muestre todas las columnas

In [16]:
df_netflix = pd.read_csv("../datos/netflix_originals.csv")
df_netflix_titles = pd.read_csv("../datos/netflix_titles.csv")

In [17]:
df_netflix.head()

,Unnamed: 0,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi

In [18]:
df_netflix.drop(columns = ["Unnamed: 0"], inplace = True) 
# elimina primera columna "Unnamed" no aporta valor
# inplace guarda el cambio

In [19]:
df_netflix.head()

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi

In [23]:
df_netflix_titles.head()

,Unnamed: 0,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [24]:
df_netflix_titles.drop(columns = ["Unnamed: 0"], inplace = True)
#Columna "unnamed" no aporta valor

In [26]:
df_netflix_titles.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [30]:
#Veo la información que contiene cada data_set
df_netflix.columns

Index(['Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language'], dtype='object')

In [31]:
df_netflix_titles.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

### Tengo 2 dataframes:
1. El primero contiene id, título, género, premiere, duración, imdb e idioma.
2. El segundo contiene id, tipo, título, director, reparto, país, día añadido, año lanzamiento, rating, duración, listed_in y descripción.
3. De ambos he eliminado la columna "Unnamed: 0" por no aportar valor.
4. En común tenemos el título y la duración.

In [38]:
# Busco títulos duplicados, porque no debería haberlos duplicados 
df_netflix.duplicated(subset = "Title").sum()
# Resultado 0 ok

np.int64(0)

In [41]:
# Busco títulos y IDs duplicados, porque no debería haberlos duplicados 
df_netflix_titles.duplicated(subset = ["title", "show_id"]).sum()
# Resultado 0 ok

np.int64(0)

In [84]:
#Hago un merge de las dos tablas por el dato que tienen en común, que en este caso es el título, pero las columnas tienen distinto nombre en los dos data frames.

df_merge = df_netflix_titles.merge(df_netflix, left_on = "title", right_on = "Title", how = "left")
df_merge

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90.0,7.5,English
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,NaN,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,NaN,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# La columna duration tiene datos equivocados, por ejemplo, "2 seasons", además, el formato es de tipo string, i.e. "90 min", lo que hace imposible aplicar operaciones matemáticas.

In [ ]:
#Columna "Title" ahora se encuentra repetida, así que la eliminamos.
df_merge.drop(columns = ["Title"], inplace = True)

In [106]:
# Cuento cantidad de títulos originales que encuentro en el DataFrame de Originiales
# Contando cantidad de NO nulos para cada columna
df_merge.shape[0] - df_merge.isnull().sum()

show_id         8807
type            8807
title           8807
director        6173
cast            7982
country         7976
date_added      8797
release_year    8807
rating          8803
duration        3994
listed_in       8807
description     8807
Title            513
Genre            513
Premiere         513
Runtime          513
IMDB Score       513
Language         513
dtype: int64

Hay 513 títulos originales de Netflix.

No se puede determinar si hay diferencias significativas entre la puntuación IMDB de las producciones originales de Netflix y las que no lo son, puesto que no tenemos la puntuación para aquellas que no lo son.

In [85]:
# Reviso tipos de datos 
df_merge.dtypes

show_id          object
type             object
title            object
director         object
cast             object
country          object
date_added       object
release_year      int64
rating           object
duration         object
listed_in        object
description      object
Title            object
Genre            object
Premiere         object
Runtime         float64
IMDB Score      float64
Language         object
dtype: object

In [ ]:
# El formato de duration no es correcto.
# El tipo de la fecha debería ser int para poder operar sobre ella.
# Misma situación con la duración, debería ser int.

In [88]:
# Busco los valores únicos de las distintas columnas:
for column in df_merge.select_dtypes("object").columns:
    print(column.upper())
    print(df_merge[column].unique())
    print("\n------------\n")

SHOW_ID
['s1' 's2' 's3' ... 's8805' 's8806' 's8807']

------------

TYPE
['Movie' 'TV Show']

------------

TITLE
['Dick Johnson Is Dead' 'Blood & Water' 'Ganglands' ... 'Zombieland'
 'Zoom' 'Zubaan']

------------

DIRECTOR
['Kirsten Johnson' nan 'Julien Leclercq' ... 'Majid Al Ansari'
 'Peter Hewitt' 'Mozez Singh']

------------

CAST
[nan
 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng'
 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera'
 ...
 'Jesse Eisenberg, Woody Harrelson, Emma Stone, Abigail Breslin, Amber Heard, Bill Murray, Derek Graf'
 'Tim Allen, Courteney Cox, Chevy Chase, Kate Mara, Ryan Newman, Michael Cassidy, Spencer Breslin, Rip Torn, Kevin Zegers'
 'Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy']

------------

COUNTRY
['United States' 'South Africa' nan 'India'
 'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia'
 'United Kingdom' 'Germany, Czech Republic' 'Mexico' 'Turkey' 'Australia'
 'United States, India, France' 'Finland' 'China, Canada, United States'
 'South Africa, United States, Japan' 'Nigeria' 'Japan'
 'Spain, United States' 'France' 'Belgium' 'United Kingdom, United States'
 'United States, United Kingdom' 'France, United States' 'South Korea'
 'Spain' 'United States, Singapore' 'United Kingdom, Australia, France'
 'United Kingdom, Australia, France, United States'
 'United States, Canada' 'Germany, United States'
 'South Africa, United States' 'United States, Mexico'
 'United States, Italy, France, Japan'
 'United States, Italy, Romania, United Kingdom'
 'Australia, United States' 'Argentina, Venezuela'
 'United States, United Kingdom, Canada' 'China, Hong Kong' 'Russia'
 'Canada' 'Hong Kong' 'United States, China, Hong Kong'
 'Italy, United States' 'United States, Germany'
 'United Kingdom, Canada, United States' ', South Korea' 'Ireland'
 'India, Nepal' 'New Zealand, Australia, France, United States' 'Italy'
 'Italy, Brazil, Greece' 'Argentina' 'Jordan' 'Colombia'
 'United States, Japan' 'Belgium, United Kingdom'
 'Switzerland, United Kingdom, Australia' 'Israel, United States'
 'Canada, United States' 'Brazil' 'Argentina, Spain' 'Taiwan'
 'United States, Nigeria' 'Bulgaria, United States'
 'Spain, United Kingdom, United States' 'United States, China'
 'United States, France' 'Spain, France, United Kingdom, United States'
 ', France, Algeria' 'Poland' 'Germany'
 'France, Israel, Germany, United States, United Kingdom' 'New Zealand'
 'Saudi Arabia' 'Thailand' 'Indonesia' 'Egypt, Denmark, Germany'
 'United States, Switzerland' 'Hong Kong, Canada, United States'
 'Kuwait, United States' 'France, Canada, United States, Spain'
 'France, Netherlands, Singapore' 'France, Belgium'
 'Ireland, United States, United Kingdom' 'Egypt' 'Malaysia' 'Israel'
 'Australia, New Zealand' 'United Kingdom, Germany' 'Belgium, Netherlands'
 'South Korea, Czech Republic' 'Australia, Germany' 'Vietnam'
 'United Kingdom, Belgium' 'United Kingdom, Australia, United States'
 'France, Japan, United States'
 'United Kingdom, Germany, Spain, United States'
 'United Kingdom, United States, France, Italy'
 'United States, Germany, Canada'
 'United States, France, Italy, United Kingdom'
 'United States, United Kingdom, Germany, Hungary'
 'United States, New Zealand' 'Sweden' 'China' 'Lebanon' 'Romania'
 'Finland, Germany' 'Lebanon, Syria' 'Philippines' 'Iceland' 'Denmark'
 'United States, India' 'Philippines, Singapore, Indonesia'
 'China, United States, Canada' 'Lebanon, United Arab Emirates'
 'Canada, United States, Denmark' 'United Arab Emirates'
 'Mexico, France, Colombia' 'Netherlands' 'Germany, United States, France'
 'United States, Bulgaria'
 'United Kingdom, France, Germany, United States' 'Norway, Denmark'
 'Syria, France, Lebanon, Qatar' 'United States, Czech Republic'
 'Mauritius' 'Canada, South Africa' 'Austria' 'Mexico, Brazil'
 'Germany, France' 'Mexico, United States'
 'United Kingdom, France, Spain, United States' 'United States, Australia'
 'United States, United Kingdom, France' 'United States, Russia'
 'United States, United Kingdom, New Zealand' 'Australia, United Kingdom'
 'Canada, Nigeria, United States'
 'France, United States, United Kingdom, Canada' 'France, United Kingdom'
 'India, United Kingdom' 'Canada, United States, Mexico'
 'United Kingdom, Germany, United States'
 'Czech Republic, United Kingdom, United States' 'China, United Kingdom'
 'Italy, United Kingdom' 'China, Taiwan'
 'United States, Brazil, Japan, Spain, India'
 'United States, China, United Kingdom' 'Cameroon'
 'Lebanon, Palestine, Denmark, Qatar' 'Japan, United States'
 'Uruguay, Germany' 'Egypt, Saudi Arabia'
 'United Kingdom, France, Poland, Germany, United States'
 'Ireland, Switzerland, United Kingdom, France, United States'
 'United Kingdom, South Africa, France'
 'Ireland, United Kingdom, France, Germany' 'Russia, United States'
 'United Kingdom, United States, France' 'United Kingdom,'
 'United States, India, United Kingdom' 'Kenya' 'Spain, Argentina'
 'India, United Kingdom, France, Qatar' 'Belgium, France'
 'Argentina, Chile' 'United States, Thailand' 'Chile, Brazil'
 'United States, Colombia' 'Canada, United States, United Kingdom'
 'Uruguay' 'Luxembourg' 'United States, Cambodia, Romania' 'Bangladesh'
 'Spain, Belgium, United States'
 'United Kingdom, United States, Australia'
 'Canada, United States, France' 'Portugal, United States'
 'Portugal, Spain' 'India, United States' 'United Kingdom, Ireland'
 'United Kingdom, Spain, United States' 'Hungary, United States'
 'United States, South Korea' 'Canada, United States, Cayman Islands'
 'India, France' 'France, Canada' 'Canada, Hungary, United States'
 'Norway' 'Canada, United Kingdom, United States'
 'United Kingdom, Germany, France, United States' 'Denmark, United States'
 'Senegal' 'France, Algeria'
 'United Kingdom, Finland, Germany, United States, Australia, Japan, France, Ireland'
 'Philippines, Canada, United Kingdom, United States'
 'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong'
 'Singapore' 'Kuwait' 'United States, France, Serbia'
 'United States, Italy' 'Spain, Italy'
 'United States, Ireland, United Kingdom, India'
 'United Kingdom, Singapore' 'Hong Kong, United States'
 'United States, Malta, France, United Kingdom'
 'United States, China, Canada' 'Canada, United States, Ireland'
 'Lebanon, Canada, France' 'Japan, Canada, United States'
 'Spain, France, Canada' 'Denmark, Singapore, Canada, United States'
 'United States, France, Denmark' 'United States, China, Colombia'
 'Spain, Thailand, United States' 'Mexico, Spain'
 'Ireland, Luxembourg, Belgium' 'China, United States' 'Canada, Belgium'
 'Canada, United Kingdom'
 'Lebanon, United Arab Emirates, France, Switzerland, Germany'
 'France, Belgium, Italy' 'Lebanon, United States, United Arab Emirates'
 'Lebanon, France' 'France, Lebanon' 'France, Lebanon, United Kingdom'
 'France, Norway, Lebanon, Belgium'
 'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands'
 'United States, United Kingdom, India' 'Indonesia, Netherlands'
 'Turkey, South Korea' 'Serbia, United States' 'Namibia'
 'United Kingdom, Kenya' 'United Kingdom, France, Germany, Spain'
 'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany'
 'Thailand, United States' 'United States, France, Canada, Belgium'
 'United Kingdom, China' 'Germany, China, United Kingdom'
 'Australia, New Zealand, United States'
 'Hong Kong, Iceland, United States' 'France, Australia, Germany'
 'United States, Belgium, Canada, France' 'South Africa, Angola'
 'United States, Philippines'
 'United States, United Kingdom, Canada, China'
 'United States, Canada, United Kingdom' 'Turkey, United States'
 'Peru, Germany, Norway' 'Mozambique' 'Brazil, France'
 'China, Spain, South Korea, United States' 'Spain, Germany'
 'Hong Kong, China' 'France, Belgium, Luxembourg, Cambodia,'
 'United Kingdom, Australia' 'Belarus' 'Indonesia, United Kingdom'
 'Switzerland, France, Belgium, United States' 'Ghana'
 'Spain, France, Canada, United States' 'Chile, Italy'
 'United Kingdom, Nigeria' 'Chile' 'France, Egypt' 'Egypt, France'
 'France, Brazil, Spain, Belgium' 'Egypt, Algeria'
 'Canada, South Korea, United States' 'Nigeria, United Kingdom'
 'United States, France, Canada' 'Poland, United States'
 'United Arab Emirates, Jordan, Lebanon, Saudi Arabia'
 'United States, Mexico, Spain, Malta'
 'Saudi Arabia, United Arab Emirates' 'Zimbabwe'
 'United Kingdom, Germany, United Arab Emirates, New Zealand'
 'Romania, United States' 'Canada, Nigeria'
 'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States'
 'United Kingdom, Spain' 'Finland, France'
 'United Kingdom, Germany, United States, France'
 'India, United Kingdom, China, Canada, Japan, South Korea, United States'
 'Italy, United Kingdom, France' 'United States, Mexico, Colombia'
 'Turkey, India' 'Italy, Turkey' 'United Kingdom, United States, Japan'
 'France, Belgium, United States' 'Puerto Rico, United States, Colombia'
 'Uruguay, Argentina' 'United States, United Kingdom, Japan'
 'United States, Argentina' 'United Kingdom, Italy'
 'Ireland, United Kingdom'
 'United Kingdom, France, Belgium, Canada, United States'
 'Netherlands, Germany, Denmark, United Kingdom' 'Hungary'
 'Austria, Germany' 'Taiwan, China'
 'United Kingdom, United States, Ireland' 'South Korea, United States'
 'Brazil, United Kingdom' 'Pakistan, United States'
 'Romania, France, Switzerland, Germany' 'Romania, United Kingdom'
 'France, Malta, United States' 'Cyprus'
 'United Kingdom, France, Belgium, Ireland, United States'
 'United States, Norway, Canada' 'Kenya, United States'
 'France, South Korea, Japan, United States' 'Taiwan, Malaysia'
 'Uruguay, Argentina, Germany, Spain'
 'United States, United Kingdom, France, Germany, Japan'
 'United States, France, Japan' 'United Kingdom, France, United States'
 'Spain, France, United States' 'Indonesia, South Korea, Singapore'
 'United States, Spain' 'Netherlands, Germany, Italy, Canada'
 'Spain, Germany, Denmark, United States' 'Norway, Sweden'
 'South Korea, Canada, United States, China' 'Argentina, Uruguay, Serbia'
 'France, Japan' 'Mauritius, South Africa' 'United States, Poland'
 'United Kingdom, United States, Germany, Denmark, Belgium, Japan'
 'India, Germany' 'India, United Kingdom, Canada, United States'
 'Philippines, United States' 'Romania, Bulgaria, Hungary'
 'Uruguay, Guatemala' 'France, Senegal, Belgium' 'United Kingdom, Canada'
 'Mexico, United States, Spain, Colombia' 'Canada, Norway'
 'Singapore, United States' 'Finland, Germany, Belgium'
 'United Kingdom, France' 'United States, Chile'
 'United Kingdom, Japan, United States' 'Spain, United Kingdom'
 'Argentina, United States, Mexico' 'United States, South Korea, Japan'
 'Canada, Australia' 'United Kingdom, Hungary, Australia' 'Italy, Belgium'
 'United States, United Kingdom, Germany' 'Switzerland'
 'Singapore, Malaysia'
 'France, Belgium, Luxembourg, Romania, Canada, United States'
 'South Africa, Nigeria' 'Spain, France' 'United Kingdom, Hong Kong'
 'Pakistan' 'Brazil, United States'
 'Denmark, Brazil, France, Portugal, Sweden' 'India, Turkey'
 'Malaysia, Singapore, Hong Kong' 'Philippines, Singapore'
 'Australia, Canada' 'Taiwan, China, France, United States'
 'Germany, Italy' 'Colombia, Peru, United Kingdom'
 'Thailand, China, United States' 'Argentina, United States'
 'Sweden, United States' 'Uruguay, Spain, Mexico'
 'France, Luxembourg, Canada' 'Denmark, Spain' 'Chile, Argentina'
 'United Kingdom, Belgium, Sweden' 'Canada, Brazil' 'Italy, France'
 'Canada, Germany' 'Pakistan, United Arab Emirates' 'Ghana, United States'
 'Mexico, Finland' 'United Arab Emirates, United Kingdom, India'
 'Netherlands, Belgium' 'United States, Taiwan'
 'Austria, Iraq, United States' 'United Kingdom, Malawi'
 'Paraguay, Argentina' 'United Kingdom, Russia, United States'
 'India, Pakistan' 'Indonesia, Singapore' 'Spain, Belgium'
 'Iceland, Sweden, Belgium' 'Croatia' 'Uruguay, Argentina, Spain'
 'United Kingdom, Ireland, United States'
 'Canada, Germany, France, United States' 'United Kingdom, Japan'
 'Norway, Denmark, Netherlands, Sweden' 'Hong Kong, China, United States'
 'Ireland, Canada' 'Italy, Switzerland, France, Germany'
 'Mexico, Netherlands' 'United States, Sweden' 'Germany, France, Russia'
 'France, Iran, United States' 'United Kingdom, India'
 'Russia, Poland, Serbia' 'Spain, Portugal' 'Peru' 'Mexico, Argentina'
 'United Kingdom, Canada, United States, Cayman Islands'
 'Indonesia, United States'
 'United States, Israel, United Kingdom, Canada'
 'Norway, Iceland, United States' 'Czech Republic, United States'
 'United Kingdom, India, United States' 'United Kingdom, West Germany'
 'India, Australia' 'United States,'
 'Belgium, United Kingdom, United States' 'India, Germany, Austria'
 'United States, Brazil, South Korea, Mexico, Japan, Germany'
 'Spain, Mexico' 'China, Japan' 'Argentina, France'
 'China, United States, United Kingdom'
 'France, Luxembourg, United States' 'China, United States, Australia'
 'Colombia, Mexico' 'United States, Canada, Ireland' 'Chile, Peru'
 'Argentina, Italy' 'Canada, Japan, United States'
 'United Kingdom, Canada, United States, Germany'
 'Italy, Switzerland, Albania, Poland' 'United States, Japan, Canada'
 'Cambodia' 'Italy, United States, Argentina'
 'Saudi Arabia, Syria, Egypt, Lebanon, Kuwait'
 'United States, Canada, Indonesia, United Kingdom, China, Singapore'
 'Spain, Colombia'
 'United Kingdom, South Africa, Australia, United States' 'Bulgaria'
 'Argentina, Brazil, France, Poland, Germany, Denmark'
 'United Kingdom, Spain, United States, Germany' 'Philippines, Qatar'
 'Netherlands, Belgium, Germany, Jordan'
 'United Arab Emirates, United States' 'Norway, Germany, Sweden'
 'South Korea, China' 'Georgia' 'Soviet Union, India'
 'Australia, United Arab Emirates' 'Canada, Germany, South Africa'
 'South Korea, China, United States' 'India, Soviet Union' 'India, Mexico'
 'Georgia, Germany, France' 'United Arab Emirates, Romania'
 'India, Malaysia' 'Germany, Jordan, Netherlands'
 'Turkey, France, Germany, Poland' 'Greece, United States'
 'France, United Kingdom, United States' 'Norway, Germany'
 'France, Morocco' 'Cambodia, United States' 'United States, Denmark'
 'United States, Colombia, Mexico'
 'United Kingdom, Italy, Israel, Peru, United States'
 'Argentina, Uruguay, Spain, France'
 'United Kingdom, France, United States, Belgium'
 'France, Canada, China, Cambodia'
 'United Kingdom, France, Belgium, United States' 'Chile, France'
 'Netherlands, United States' 'France, United Kingdom, India'
 'Czech Republic, Slovakia' 'Singapore, France' 'Spain, Switzerland'
 'United States, Australia, China' 'South Africa, United States, Germany'
 'United States, United Kingdom, Australia' 'Spain, Italy, Argentina'
 'Chile, Spain, Argentina, Germany' 'West Germany'
 'Austria, Czech Republic' 'Lebanon, Qatar'
 'United Kingdom, Jordan, Qatar, Iran' 'France, South Korea, Japan'
 'Israel, Germany, France' 'Canada, Japan, Netherlands'
 'United States, Hungary' 'France, Germany' 'France, Qatar'
 'United Kingdom, Germany, Canada' 'Ireland, South Africa'
 'Chile, United States, France' 'Belgium, France, Netherlands'
 'United Kingdom, Ukraine, United States'
 'Germany, Australia, France, China' 'Norway, United States'
 'United States, Bermuda, Ecuador'
 'United States, Hungary, Ireland, Canada'
 'United Kingdom, Egypt, United States'
 'United States, France, United Kingdom' 'Spain, Mexico, France'
 'United States, South Africa' 'Hong Kong, China, Singapore'
 'South Africa, China, United States' 'Denmark, France, Poland'
 'New Zealand, United Kingdom' 'Netherlands, Denmark, South Africa'
 'Iran, France' 'United Kingdom, United States, France, Germany'
 'Australia, France' 'Ireland, United Kingdom, United States'
 'United Kingdom, France, Germany' 'Canada, Luxembourg'
 'Brazil, Netherlands, United States, Colombia, Austria, Germany'
 'France, Canada, Belgium' 'Canada, France'
 'Bulgaria, United States, Spain, Canada' 'Sweden, Netherlands'
 'France, United States, Mexico'
 'Australia, United Kingdom, United Arab Emirates, Canada'
 'Australia, Armenia, Japan, Jordan, Mexico, Mongolia, New Zealand, Philippines, South Africa, Sweden, United States, Uruguay'
 'India, Iran' 'France, Belgium, Spain'
 'Denmark, Sweden, Israel, United States' 'United States, Iceland'
 'United Kingdom, Russia' 'United States, Israel, Italy, South Africa'
 'Netherlands, Denmark, France, Germany' 'South Korea, Japan'
 'United Kingdom, Pakistan' 'France, New Zealand'
 'United Kingdom, Czech Republic, United States, Germany, Bahamas'
 'China, Germany, India, United States' 'Germany, Sri Lanka'
 'United States, India, Bangladesh' 'United States, Canada, France'
 'Brazil, France, Germany' 'Germany, United States, Hong Kong, Singapore'
 'France, Germany, Switzerland'
 'Germany, France, Luxembourg, United Kingdom, United States'
 'United Kingdom, Canada, Italy' 'Czech Republic, France'
 'Taiwan, Hong Kong, United States, China' 'Germany, Australia'
 'United Kingdom, Poland, United States' 'Denmark, Zimbabwe'
 'United Kingdom, South Africa' 'Finland, Sweden, Norway, Latvia, Germany'
 'South Africa, United States, New Zealand, Canada'
 'United States, Italy, United Kingdom, Liechtenstein'
 'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom'
 'United States, Australia, Mexico'
 'United Kingdom, Czech Republic, Germany, United States'
 'France, China, Japan, United States' 'United States, South Korea, China'
 'Germany, Belgium' 'Pakistan, Norway, United States'
 'United States, Canada, Belgium, United Kingdom' 'Venezuela'
 'Canada, France, Italy, Morocco, United States' 'Canada, Spain, France'
 'United States, Indonesia' 'Spain, France, Italy'
 'United Arab Emirates, United States, United Kingdom'
 'United Kingdom, Israel, Russia' 'Spain, Cuba' 'United States, Brazil'
 'United States, France, Mexico' 'United States, Nicaragua'
 'United Kingdom, United States, Spain, Germany, Greece, Canada'
 'Italy, Canada, France' 'United Kingdom, Denmark, Canada, Croatia'
 'Italy, Germany' 'United States, France, United Kingdom, Japan'
 'United States, United Kingdom, Denmark, Sweden'
 'United States, United Kingdom, Italy'
 'United States, France, Canada, Spain' 'Russia, United States, China'
 'United States, Canada, Germany' 'Ireland, United States'
 'United States, United Arab Emirates' 'United States, Ireland'
 'Ireland, United Kingdom, Italy, United States' 'Poland,'
 'Slovenia, Croatia, Germany, Czech Republic, Qatar'
 'Canada, United Kingdom, Netherlands' 'United States, Spain, Germany'
 'India, Japan' 'China, South Korea, United States'
 'United Kingdom, France, Belgium' 'Canada, Ireland, United States'
 'United Kingdom, United States, Dominican Republic'
 'United States, Senegal' 'Germany, United Kingdom, United States'
 'South Africa, Germany, Netherlands, France'
 'Canada, United States, United Kingdom, France, Luxembourg'
 'Ireland, United States, France' 'Germany, United States, Canada'
 'United Kingdom, Germany, Canada, United States'
 'United States, France, Canada, Lebanon, Qatar'
 'Netherlands, Belgium, United Kingdom, United States'
 'France, Belgium, China, United States' 'United States, Chile, Israel'
 'United Kingdom, Norway, Denmark, Germany, Sweden'
 'Norway, Denmark, Sweden' 'China, India, Nepal'
 'Colombia, Mexico, United States' 'United Kingdom, South Korea'
 'Denmark, China' 'United States, Greece, Brazil' 'South Korea, France'
 'United States, Australia, Samoa, United Kingdom'

In [ ]:
#Hay valores nulos en directores, reparto, países y rating.

In [114]:
# Busco valores únicos

for column in df_merge.select_dtypes("object").columns:
    print(column.upper())
    print(df_merge[column].value_counts())
    print("\n------------\n")

SHOW_ID
show_id
s1       1
s5875    1
s5869    1
s5870    1
s5871    1
        ..
s2931    1
s2930    1
s2929    1
s2928    1
s8807    1
Name: count, Length: 8807, dtype: int64

------------

TYPE
type
Movie      6131
TV Show    2676
Name: count, dtype: int64

------------

TITLE
title
Dick Johnson Is Dead                     1
Ip Man 2                                 1
Hannibal Buress: Comedy Camisado         1
Turbo FAST                               1
Masha's Tales                            1
                                        ..
Love for Sale 2                          1
ROAD TO ROMA                             1
Good Time                                1
Captain Underpants Epic Choice-o-Rama    1
Zubaan                                   1
Name: count, Length: 8807, dtype: int64

------------

DIRECTOR
director
Rajiv Chilaka                     19
Raúl Campos, Jan Suter            18
Marcus Raboy                      16
Suhas Kadav                       16
Jay Karas                         14
                                  ..
Raymie Muzquiz, Stu Livingston     1
Joe Menendez                       1
Eric Bross                         1
Will Eisenberg                     1
Mozez Singh                        1
Name: count, Length: 4528, dtype: int64

------------

CAST
cast
David Attenborough                                                                                                                                                                            19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                                                       14
Samuel West                                                                                                                                                                                   10
Jeff Dunham                                                                                                                                                                                    7
David Spade, London Hughes, Fortune Feimster                                                                                                                                                   6
                                                                                                                                                                                              ..
Michael Peña, Diego Luna, Tenoch Huerta, Joaquin Cosio, José María Yazpik, Matt Letscher, Alyssa Diaz                                                                                          1
Nick Lachey, Vanessa Lachey                                                                                                                                                                    1
Takeru Sato, Kasumi Arimura, Haru, Kentaro Sakaguchi, Takayuki Yamada, Kendo Kobayashi, Ken Yasuda, Arata Furuta, Suzuki Matsuo, Koichi Yamadera, Arata Iura, Chikako Kaku, Kotaro Yoshida     1
Toyin Abraham, Sambasa Nzeribe, Chioma Chukwuka Akpotha, Chioma Omeruah, Chiwetalu Agu, Dele Odule, Femi Adebayo, Bayray McNwizu, Biodun Stephen                                               1
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy                                                          1
Name: count, Length: 7692, dtype: int64

------------

COUNTRY
country
United States                             2818
India                                      972
United Kingdom                             419
Japan                                      245
South Korea                                199
                                          ...
Romania, Bulgaria, Hungary                   1
Uruguay, Guatemala                           1
France, Senegal, Belgium                     1
Mexico, United States, Spain, Colombia       1
United Arab Emirates, Jordan                 1
Name: count, Length: 748, dtype: int64

------------

DATE_ADDED
date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
                    ...
December 4, 2016       1
November 21, 2016      1
November 19, 2016      1
November 17, 2016      1
January 11, 2020       1
Name: count, Length: 1767, dtype: int64

------------

RATING
rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

------------

DURATION
duration
2 Seasons    425
90 min       152
98 min       120
104 min      104
107 min       98
            ...
5 min          1
16 min         1
186 min        1
193 min        1
191 min        1
Name: count, Length: 185, dtype: int64

------------

LISTED_IN
listed_in
Dramas, International Movies                          362
Documentaries                                         359
Stand-Up Comedy                                       334
Comedies, Dramas, International Movies                274
Dramas, Independent Movies, International Movies      252
                                                     ...
Kids' TV, TV Action & Adventure, TV Dramas              1
TV Comedies, TV Dramas, TV Horror                       1
Children & Family Movies, Comedies, LGBTQ Movies        1
Kids' TV, Spanish-Language TV Shows, Teen TV Shows      1
Cult Movies, Dramas, Thrillers                          1
Name: count, Length: 514, dtype: int64

------------

DESCRIPTION
description
Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    4
Challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    3
A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
Multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     3
Secrets bubble to the surface after a sensual encounter and an unforeseen crime entangle two friends and a woman caught between them.                        2
                                                                                                                                                            ..
Sent away to evade an arranged marriage, a 14-year-old begins a harrowing journey of sex work and poverty in the slums of Accra.                             1
When his partner in crime goes missing, a small-time crook’s life is transformed as he dedicates himself to raising the daughter his friend left behind.     1
During 1962’s Cuban missile crisis, a troubled math genius finds himself drafted to play in a U.S.-Soviet chess match – and a deadly game of espionage.      1
A teen's discovery of a vintage Polaroid camera develops into a darker tale when she finds that whoever takes their photo with it dies soon afterward.       1
A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past.                      1
Name: count, Length: 8775, dtype: int64

------------

TITLE
Title
Dick Johnson Is Dead                     1
Seventeen                                1
The Holiday Calendar                     1
Outlaw King                              1
Loudon Wainwright III: Surviving Twin    1
                                        ..
The Old Guard                            1
The Claudia Kishi Club                   1
We Are One                               1
The Players                              1
My Own Man                               1
Name: count, Length: 513, dtype: int64

------------

GENRE
Genre
Documentary            132
Drama                   73
Comedy                  42
Romantic comedy         35
Thriller                33
                      ...
Superhero/Action         1
Dance comedy             1
Animation/Superhero      1
Drama/Horror             1
Mockumentary             1
Name: count, Length: 106, dtype: int64

------------

PREMIERE
Premiere
October 2, 2020      5
November 1, 2019     5
October 18, 2019     5
April 10, 2020       4
December 7, 2018     4
                    ..
January 17, 2020     1
January 1, 2020      1
December 26, 2019    1
December 20, 2019    1
December 13, 2014    1
Name: count, Length: 350, dtype: int64

------------

LANGUAGE
Language
English                       352
Hindi                          28
Spanish                        26
French                         18
Italian                        14
Indonesian                      9
Portuguese                      9
English/Spanish                 5
Japanese                        5
Korean                          5
Turkish                         4
German                          4
Marathi                         3
Polish                          3
English/Hindi                   2
Thai                            2
Filipino                        2
Dutch                           2
English/Japanese                2
English/Akan                    1
English/Russian                 1
English/Mandarin                1
English/Korean                  1
Khmer/English/French            1
Spanish/Basque                  1
Tamil                           1
Spanish/Catalan                 1
Norwegian                       1
English/Swedish                 1
English/Taiwanese/Mandarin      1
Spanish/English                 1
Thia/English                    1
Malay                           1
Bengali                         1
English/Arabic                  1
Swedish                         1
English/Ukranian/Russian        1
Name: count, dtype: int64

------------

In [ ]:
# En la columna duración, hay 425 filas que no corresponden con este dato, sino que es "2 Seasons", que representa un 10% de los datos.

# En la columna ratings hay 3 valores que se corresponden con la duración, y no el rating, pero son poco relevante porque representan un 0.03% del total.

In [91]:
for column in df_merge.select_dtypes("object").columns:
    print(column.upper())
    print(df_merge[column].value_counts(normalize = True)*100) #esto no tiene en cuenta los nulos
    print("\n------------\n")

SHOW_ID
show_id
s1       0.011355
s5875    0.011355
s5869    0.011355
s5870    0.011355
s5871    0.011355
           ...
s2931    0.011355
s2930    0.011355
s2929    0.011355
s2928    0.011355
s8807    0.011355
Name: proportion, Length: 8807, dtype: float64

------------

TYPE
type
Movie      69.615079
TV Show    30.384921
Name: proportion, dtype: float64

------------

TITLE
title
Dick Johnson Is Dead                     0.011355
Ip Man 2                                 0.011355
Hannibal Buress: Comedy Camisado         0.011355
Turbo FAST                               0.011355
Masha's Tales                            0.011355
                                           ...
Love for Sale 2                          0.011355
ROAD TO ROMA                             0.011355
Good Time                                0.011355
Captain Underpants Epic Choice-o-Rama    0.011355
Zubaan                                   0.011355
Name: proportion, Length: 8807, dtype: float64

------------

DIRECTOR
director
Rajiv Chilaka                     0.307792
Raúl Campos, Jan Suter            0.291592
Marcus Raboy                      0.259193
Suhas Kadav                       0.259193
Jay Karas                         0.226794
                                    ...
Raymie Muzquiz, Stu Livingston    0.016200
Joe Menendez                      0.016200
Eric Bross                        0.016200
Will Eisenberg                    0.016200
Mozez Singh                       0.016200
Name: proportion, Length: 4528, dtype: float64

------------

CAST
cast
David Attenborough                                                                                                                                                                            0.238036
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                                                       0.175395
Samuel West                                                                                                                                                                                   0.125282
Jeff Dunham                                                                                                                                                                                   0.087697
David Spade, London Hughes, Fortune Feimster                                                                                                                                                  0.075169
                                                                                                                                                                                                ...
Michael Peña, Diego Luna, Tenoch Huerta, Joaquin Cosio, José María Yazpik, Matt Letscher, Alyssa Diaz                                                                                         0.012528
Nick Lachey, Vanessa Lachey                                                                                                                                                                   0.012528
Takeru Sato, Kasumi Arimura, Haru, Kentaro Sakaguchi, Takayuki Yamada, Kendo Kobayashi, Ken Yasuda, Arata Furuta, Suzuki Matsuo, Koichi Yamadera, Arata Iura, Chikako Kaku, Kotaro Yoshida    0.012528
Toyin Abraham, Sambasa Nzeribe, Chioma Chukwuka Akpotha, Chioma Omeruah, Chiwetalu Agu, Dele Odule, Femi Adebayo, Bayray McNwizu, Biodun Stephen                                              0.012528
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy                                                         0.012528
Name: proportion, Length: 7692, dtype: float64

------------

COUNTRY
country
United States                             35.330993
India                                     12.186560
United Kingdom                             5.253260
Japan                                      3.071715
South Korea                                2.494985
                                            ...
Romania, Bulgaria, Hungary                 0.012538
Uruguay, Guatemala                         0.012538
France, Senegal, Belgium                   0.012538
Mexico, United States, Spain, Colombia     0.012538
United Arab Emirates, Jordan               0.012538
Name: proportion, Length: 748, dtype: float64

------------

DATE_ADDED
date_added
January 1, 2020      1.239059
November 1, 2019     1.011709
March 1, 2018        0.852563
December 31, 2019    0.841196
October 1, 2018      0.807093
                       ...
December 4, 2016     0.011368
November 21, 2016    0.011368
November 19, 2016    0.011368
November 17, 2016    0.011368
January 11, 2020     0.011368
Name: proportion, Length: 1767, dtype: float64

------------

RATING
rating
TV-MA       36.430762
TV-14       24.537090
TV-PG        9.803476
R            9.076451
PG-13        5.566284
TV-Y7        3.794161
TV-Y         3.487447
PG           3.260252
TV-G         2.499148
NR           0.908781
G            0.465750
TV-Y7-FV     0.068159
NC-17        0.034079
UR           0.034079
74 min       0.011360
84 min       0.011360
66 min       0.011360
Name: proportion, dtype: float64

------------

DURATION
duration
2 Seasons    10.640961
90 min        3.805709
98 min        3.004507
104 min       2.603906
107 min       2.453681
               ...
5 min         0.025038
16 min        0.025038
186 min       0.025038
193 min       0.025038
191 min       0.025038
Name: proportion, Length: 185, dtype: float64

------------

LISTED_IN
listed_in
Dramas, International Movies                          4.110367
Documentaries                                         4.076303
Stand-Up Comedy                                       3.792438
Comedies, Dramas, International Movies                3.111162
Dramas, Independent Movies, International Movies      2.861360
                                                        ...
Kids' TV, TV Action & Adventure, TV Dramas            0.011355
TV Comedies, TV Dramas, TV Horror                     0.011355
Children & Family Movies, Comedies, LGBTQ Movies      0.011355
Kids' TV, Spanish-Language TV Shows, Teen TV Shows    0.011355
Cult Movies, Dramas, Thrillers                        0.011355
Name: proportion, Length: 514, dtype: float64

------------

DESCRIPTION
description
Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    0.045418
Challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    0.034064
A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 0.034064
Multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     0.034064
Secrets bubble to the surface after a sensual encounter and an unforeseen crime entangle two friends and a woman caught between them.                        0.022709
                                                                                                                                                               ...
Sent away to evade an arranged marriage, a 14-year-old begins a harrowing journey of sex work and poverty in the slums of Accra.                             0.011355
When his partner in crime goes missing, a small-time crook’s life is transformed as he dedicates himself to raising the daughter his friend left behind.     0.011355
During 1962’s Cuban missile crisis, a troubled math genius finds himself drafted to play in a U.S.-Soviet chess match – and a deadly game of espionage.      0.011355
A teen's discovery of a vintage Polaroid camera develops into a darker tale when she finds that whoever takes their photo with it dies soon afterward.       0.011355
A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past.                      0.011355
Name: proportion, Length: 8775, dtype: float64

------------

TITLE
Title
Dick Johnson Is Dead                     0.194932
Seventeen                                0.194932
The Holiday Calendar                     0.194932
Outlaw King                              0.194932
Loudon Wainwright III: Surviving Twin    0.194932
                                           ...
The Old Guard                            0.194932
The Claudia Kishi Club                   0.194932
We Are One                               0.194932
The Players                              0.194932
My Own Man                               0.194932
Name: proportion, Length: 513, dtype: float64

------------

GENRE
Genre
Documentary            25.730994
Drama                  14.230019
Comedy                  8.187135
Romantic comedy         6.822612
Thriller                6.432749
                         ...
Superhero/Action        0.194932
Dance comedy            0.194932
Animation/Superhero     0.194932
Drama/Horror            0.194932
Mockumentary            0.194932
Name: proportion, Length: 106, dtype: float64

------------

PREMIERE
Premiere
October 2, 2020      0.974659
November 1, 2019     0.974659
October 18, 2019     0.974659
April 10, 2020       0.779727
December 7, 2018     0.779727
                       ...
January 17, 2020     0.194932
January 1, 2020      0.194932
December 26, 2019    0.194932
December 20, 2019    0.194932
December 13, 2014    0.194932
Name: proportion, Length: 350, dtype: float64

------------

LANGUAGE
Language
English                       68.615984
Hindi                          5.458090
Spanish                        5.068226
French                         3.508772
Italian                        2.729045
Indonesian                     1.754386
Portuguese                     1.754386
English/Spanish                0.974659
Japanese                       0.974659
Korean                         0.974659
Turkish                        0.779727
German                         0.779727
Marathi                        0.584795
Polish                         0.584795
English/Hindi                  0.389864
Thai                           0.389864
Filipino                       0.389864
Dutch                          0.389864
English/Japanese               0.389864
English/Akan                   0.194932
English/Russian                0.194932
English/Mandarin               0.194932
English/Korean                 0.194932
Khmer/English/French           0.194932
Spanish/Basque                 0.194932
Tamil                          0.194932
Spanish/Catalan                0.194932
Norwegian                      0.194932
English/Swedish                0.194932
English/Taiwanese/Mandarin     0.194932
Spanish/English                0.194932
Thia/English                   0.194932
Malay                          0.194932
Bengali                        0.194932
English/Arabic                 0.194932
Swedish                        0.194932
English/Ukranian/Russian       0.194932
Name: proportion, dtype: float64

------------

In [ ]:
# Los tipos más habituales de contenido en Netflix son películas (un 70%) y series de TV (30%).
# El 36% tienes un rating para mayores, y un 25% son aptas para menores de 14 años.

# Los géneros más comunes son:
# Documentales: 26% y Drama: 14%.

# El 69% del contenido está en inglés.

In [92]:
df_netflix_titles.shape

(8807, 12)

In [93]:
df_netflix.shape

(513, 6)

In [94]:
df_merge.shape

(8807, 18)

In [107]:
df_merge.describe(include = "O").T

,count,unique,top,freq
show_id,8807,8807,s1,1
type,8807,2,Movie,6131
title,8807,8807,Dick Johnson Is Dead,1
director,6173,4528,Rajiv Chilaka,19
cast,7982,7692,David Attenborough,19
country,7976,748,United States,2818
date_added,8797,1767,"January 1, 2020",109
rating,8803,17,TV-MA,3207
duration,3994,185,2 Seasons,425
listed_in,8807,514,"Dramas, International Movies",362
description,8807,8775,"Paranormal activity at a lush, abandoned prope...",4
Title,513,513,Dick Johnson Is Dead,1
Genre,513,106,Documentary,132
Premiere,513,350,"October 2, 2020",5
Language,513,37,English,352

In [ ]:
#Habiendo 8807 registros únicos del show id, que es el tamaño del dataframe, quiere decir que son válidos como identificadores únicos de cada fila.

In [109]:
# Contar cantidad de Nulos para cada columna
df_merge.isnull().sum()

np.round(df_merge.isnull().sum() / df_merge.shape[0]*100, 2)

show_id          0.00
type             0.00
title            0.00
director        29.91
cast             9.37
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration        54.65
listed_in        0.00
description      0.00
Title           94.18
Genre           94.18
Premiere        94.18
Runtime         94.18
IMDB Score      94.18
Language        94.18
dtype: float64

In [ ]:
# Hay muchos valores nulos.
#Hay muchas columnas en las que faltan datos. Particularmente llama la atención la duración, donde falta casi más de la mitad de los registros, siendo un rato importante por ejemplo, para los algoritmos de recomendación al usuario.

# Ejercicios

In [117]:
#1.1 Selecciono todas las filas con el contenido Movie
df_merge.loc[df_merge['type'] == 'Movie']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90.0,7.5,English
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,NaN,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...,NaN,NaN,NaN,NaN,NaN,NaN
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s...",NaN,NaN,NaN,NaN,NaN,NaN
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,NaN,NaN,NaN,NaN,NaN,NaN
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,NaN,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...,NaN,NaN,NaN,NaN,NaN,NaN
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
# 1.2 Títulos y duración de todos los contenidos que sean "TV show"
df_merge.loc[df_merge["type"] == 'TV Show', ["title", "duration"]]

                      title   duration
1             Blood & Water  2 Seasons
2                 Ganglands        NaN
3     Jailbirds New Orleans        NaN
4              Kota Factory  2 Seasons
5             Midnight Mass        NaN
...                     ...        ...
8795        Yu-Gi-Oh! Arc-V  2 Seasons
8796             Yunus Emre  2 Seasons
8797              Zak Storm        NaN
8800     Zindagi Gulzar Hai        NaN
8803            Zombie Dumb  2 Seasons

[2676 rows x 2 columns]

In [119]:
# 1.3 Todas las filas donde el país sea "TV show"
df_merge.loc[df_merge['country'] == 'United States']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90.0,7.5,English
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...,NaN,NaN,NaN,NaN,NaN,NaN
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,NaN,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...,NaN,NaN,NaN,NaN,NaN,NaN
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,NaN,Comedies,Mourning the loss of their beloved junior high...,NaN,NaN,NaN,NaN,NaN,NaN
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,NaN,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8791,s8792,Movie,Young Adult,Jason Reitman,"Charlize Theron, Patton Oswalt, Patrick Wilson...",United States,"November 20, 2019",2011,R,NaN,"Comedies, Dramas, Independent Movies",When a divorced writer gets a letter from an o...,NaN,NaN,NaN,NaN,NaN,NaN
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,"Dennis Quaid, Rene Russo, Sean Faris, Katija P...",United States,"November 20, 2019",2005,PG,NaN,"Children & Family Movies, Comedies",When a father of eight and a mother of 10 prep...,NaN,NaN,NaN,NaN,NaN,NaN
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",NaN,NaN,NaN,NaN,NaN,NaN
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,NaN,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,NaN,NaN,NaN,NaN,NaN,NaN
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,NaN,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
#1.4 Muestro todas las películas (type "Movie") y las columnas title y director.
df_merge.loc[df_merge["type"] == 'Movie', ["title", "director"]]

                                 title                       director
0                 Dick Johnson Is Dead                Kirsten Johnson
6     My Little Pony: A New Generation  Robert Cullen, José Luis Ucha
7                              Sankofa                   Haile Gerima
9                         The Starling                 Theodore Melfi
12                        Je Suis Karl            Christian Schwochow
...                                ...                            ...
8801                           Zinzana                Majid Al Ansari
8802                            Zodiac                  David Fincher
8804                        Zombieland                Ruben Fleischer
8805                              Zoom                   Peter Hewitt
8806                            Zubaan                    Mozez Singh

[6131 rows x 2 columns]

In [132]:
#1.5 Muestro los títulos y géneros de las producciones lanzadas en 2018.
df_merge.loc[df_merge["release_year"] == 2018, ["title", "listed_in"]]

,title,listed_in
21,Resurrection: Ertugrul,"International TV Shows, TV Action & Adventure,..."
37,Angry Birds,"Kids' TV, TV Comedies"
73,King of Boys,"Dramas, International Movies"
94,Show Dogs,"Children & Family Movies, Comedies"
96,If I Leave Here Tomorrow: A Film About Lynyrd ...,"Documentaries, Music & Musicals"
...,...,...
8732,White Chamber,"Sci-Fi & Fantasy, Thrillers"
8743,Wildlife,"Dramas, Independent Movies"
8774,يوم الدين,"Dramas, Independent Movies, International Movies"
8775,Yeh Meri Family,"International TV Shows, TV Comedies"
8803,Zombie Dumb,"Kids' TV, Korean TV Shows, TV Comedies"

In [136]:
#1.6 Muestro el "title" filas donde la columna "director" esté vacía.

pd.DataFrame(df_merge.loc[pd.isnull(df_merge["director"]), "title"])

                                    title
1                           Blood & Water
3                   Jailbirds New Orleans
4                            Kota Factory
10    Vendetta: Truth, Lies and The Mafia
14        Crime Stories: India Detectives
...                                   ...
8795                      Yu-Gi-Oh! Arc-V
8796                           Yunus Emre
8797                            Zak Storm
8800                   Zindagi Gulzar Hai
8803                          Zombie Dumb

[2634 rows x 1 columns]

In [139]:
# Selecciona las primeras 5 filas del conjunto de datos y muestra solo las columnas title, director y country.

df_merge.iloc[0:5,[2,3,5]]

                   title         director        country
0   Dick Johnson Is Dead  Kirsten Johnson  United States
1          Blood & Water              NaN   South Africa
2              Ganglands  Julien Leclercq            NaN
3  Jailbirds New Orleans              NaN            NaN
4           Kota Factory              NaN          India

In [141]:
for i,j in enumerate(df_merge.columns):
    print(f'{i}:{j}')

0:show_id
1:type
2:title
3:director
4:cast
5:country
6:date_added
7:release_year
8:rating
9:duration
10:listed_in
11:description
12:Title
13:Genre
14:Premiere
15:Runtime
16:IMDB Score
17:Language

In [143]:
# - Selecciona las primeras 10 filas del dataset y muestra las columnas desde la segunda hasta la quinta (incluidas).

df_merge.iloc[0:10,2:6]

,title,director,cast,country
0,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States
1,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa
2,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,Jailbirds New Orleans,NaN,NaN,NaN
4,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India
5,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN
6,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN
7,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin..."
8,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom
9,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States

In [144]:
# Muestra las últimas 7 filas del dataset y selecciona las columnas title, director, y country usando índices posicionales.

df_merge.iloc[-7:,[2,3,5]]

                   title         director                       country
8800  Zindagi Gulzar Hai              NaN                      Pakistan
8801             Zinzana  Majid Al Ansari  United Arab Emirates, Jordan
8802              Zodiac    David Fincher                 United States
8803         Zombie Dumb              NaN                           NaN
8804          Zombieland  Ruben Fleischer                 United States
8805                Zoom     Peter Hewitt                 United States
8806              Zubaan      Mozez Singh                         India

In [145]:
# Selecciona las filas desde la 15 hasta la 25 (incluidas) y muestra las primeras 4 columnas.

df_merge.iloc[15:26,:5]

,show_id,type,title,director,cast
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,..."
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri..."
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh..."
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá..."
20,s21,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,NaN
21,s22,TV Show,Resurrection: Ertugrul,NaN,"Engin Altan Düzyatan, Serdar Gökhan, Hülya Dar..."
22,s23,Movie,Avvai Shanmughi,K.S. Ravikumar,"Kamal Hassan, Meena, Gemini Ganesan, Heera Raj..."
23,s24,Movie,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore","Maisie Benson, Paul Killam, Kerry Gudjohnsen, ..."
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi..."
25,s26,TV Show,Love on the Spectrum,NaN,Brooke Satchwell

In [147]:
# Muestra las filas 20 a 30 y solo las columnas title, release_year, y rating usando índices posicionales.

df_merge.iloc[20:31,[2,7,8]]

                                              title  release_year rating
20  Monsters Inside: The 24 Faces of Billy Milligan          2021  TV-14
21                           Resurrection: Ertugrul          2018  TV-14
22                                  Avvai Shanmughi          1996  TV-PG
23     Go! Go! Cory Carson: Chrissy Takes the Wheel          2021   TV-Y
24                                            Jeans          1998  TV-14
25                             Love on the Spectrum          2021  TV-14
26                                   Minsara Kanavu          1997  TV-PG
27                                        Grown Ups          2010  PG-13
28                                       Dark Skies          2013  PG-13
29                                         Paranoia          2013  PG-13
30                                  Ankahi Kahaniya          2021  TV-14